from flask import Flask, render_template, request, redirect, url_for, session, jsonify
from configparser import ConfigParser
import database
import zoho_api
import requests
import json
import time
import datetime
import os
from datetime import timedelta

from werkzeug.middleware.proxy_fix import ProxyFix
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from cryptography.fernet import Fernet

config = ConfigParser()
config.read('config.ini')

# ── Secret key validation ────────────────────────────────────────────────────
# Env var (injected by systemd) takes priority over config.ini
_secret_key = os.environ.get('APP_SECRET_KEY') or config['APP'].get('secret_key', '')
_DEFAULT_KEYS = {'', 'dev_key', 'super_secret_random_key_change_in_production', 'REPLACE_WITH_RANDOM_KEY_SEE_COMMENT_ABOVE'}
if _secret_key in _DEFAULT_KEYS:
    raise RuntimeError(
        "FATAL: secret_key is not set or is using the default/placeholder value. "
        "Generate a random key with: python3 -c \"import secrets; print(secrets.token_hex(32))\" "
        "and set it via APP_SECRET_KEY in the systemd service or in config.ini before starting."
    )

# ── Token encryption key ─────────────────────────────────────────────────────
# Stored in environment variable TOKEN_ENCRYPTION_KEY (generated by setup script).
# Fall back to a key derived from the app secret for backward-compatibility during
# first-run, but emit a warning so the admin knows to set the env var.
_raw_fernet_key = os.environ.get('TOKEN_ENCRYPTION_KEY', '')
if _raw_fernet_key:
    _cipher = Fernet(_raw_fernet_key.encode())
else:
    import base64, hashlib
    _derived = base64.urlsafe_b64encode(hashlib.sha256(_secret_key.encode()).digest())
    _cipher = Fernet(_derived)
    print("WARNING: TOKEN_ENCRYPTION_KEY env var not set. Using derived key. "
          "Set TOKEN_ENCRYPTION_KEY in /etc/systemd/system/zohomap.service for production.")

def encrypt_token(token: str) -> str:
    return _cipher.encrypt(token.encode()).decode()

def decrypt_token(token: str) -> str:
    try:
        return _cipher.decrypt(token.encode()).decode()
    except Exception:
        return ''

app = Flask(__name__)
app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1, x_prefix=1)
app.secret_key = _secret_key

# ── Session lifetime ─────────────────────────────────────────────────────────
app.permanent_session_lifetime = timedelta(hours=8)

# ── Rate limiting ─────────────────────────────────────────────────────────────
limiter = Limiter(
    app=app,
    key_func=get_remote_address,
    default_limits=["500 per hour"],
    storage_uri="memory://"  # Switch to redis:// on AWS for multi-instance safety
)
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY') or config['GOOGLE'].get('maps_api_key', '')

# Initialize Database
database.init_db()

LOG_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'debug.log')

# Derive CRM base URL from API URL for record links
# Derive Zoho base TLD from API URL for record links
ZOHO_TLD = "zoho.com"
if "zohoapis.eu" in zoho_api.ZOHO_API_URL: ZOHO_TLD = "zoho.eu"
elif "zohoapis.com.au" in zoho_api.ZOHO_API_URL: ZOHO_TLD = "zoho.com.au"
elif "zohoapis.in" in zoho_api.ZOHO_API_URL: ZOHO_TLD = "zoho.in"
elif "zohoapis.jp" in zoho_api.ZOHO_API_URL: ZOHO_TLD = "zoho.jp"


def log_debug(msg):
    print(msg)
    try:
        with open(LOG_FILE, 'a') as f:
            ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            f.write(f"[{ts}] {msg}\n")
    except Exception as e:
        print(f"Error writing to {LOG_FILE}: {e}")

def extract_val(val):
    if isinstance(val, dict):
        return val.get('name', val.get('display_value', str(val)))
    return val

def geocode_address(address):
    cached = database.get_cached_geocode(address)
    if cached:
        return cached['lat'], cached['lng']
    
    log_debug(f"Geocoding new address (this may take a moment): {address}")
    url = f"https://maps.googleapis.com/maps/api/geocode/json?address={requests.utils.quote(address)}&key={GOOGLE_MAPS_API_KEY}"
    try:
        resp = requests.get(url, timeout=5).json()
        if resp.get('status') == 'OK' and len(resp.get('results', [])) > 0:
            loc = resp['results'][0]['geometry']['location']
            database.set_cached_geocode(address, loc['lat'], loc['lng'])
            log_debug(f"Success! Cached coordinates for {address}.")
            return loc['lat'], loc['lng']
        else:
            log_debug(f"Geocode failed for {address}: {resp.get('status')}")
    except Exception as e:
        log_debug(f"Error geocoding {address}: {e}")
    return None, None

@app.route('/health')
@limiter.exempt
def health():
    """Health check endpoint for AWS load balancers and monitoring."""
    try:
        conn = database.get_db_connection()
        conn.close()
        db_status = 'connected'
    except Exception:
        db_status = 'error'
    status = 'ok' if db_status == 'connected' else 'degraded'
    code = 200 if status == 'ok' else 503
    return jsonify({'status': status, 'db': db_status}), code

@app.route('/api/logs')
@limiter.limit("30 per minute")
def get_logs():
    if 'access_token' not in session:
        return jsonify({'error': 'Unauthorized'}), 401
    # Logs contain PII (user names, record data) — admin-only
    if not session.get('is_admin', False):
        return jsonify({'error': 'Forbidden'}), 403
    try:
        with open(LOG_FILE, 'r') as f:
            lines = f.readlines()
            if not lines:
                return jsonify({'logs': ['Waiting for server activity...']})
            return jsonify({'logs': [line.strip() for line in lines[-50:]]})
    except FileNotFoundError:
        return jsonify({'logs': ['Waiting for server activity...']})

@app.route('/api/logs/clear', methods=['POST'])
@limiter.limit("10 per minute")
def clear_server_logs():
    if 'access_token' not in session:
        return jsonify({'error': 'Unauthorized'}), 401
    if not session.get('is_admin', False):
        return jsonify({'error': 'Forbidden'}), 403
    try:
        with open(LOG_FILE, 'w') as f:
            ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            f.write(f"[{ts}] --- Logs cleared by {session.get('user_name')} ---\n")
        return jsonify({'success': True})
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@app.before_request
def make_session_permanent():
    session.permanent = True

@app.before_request
def check_token_refresh():
    if 'access_token' in session and 'expires_at' in session:

        # 1. Refresh token if near expiry
        if time.time() > session['expires_at'] - 300:
            if 'refresh_token' in session:
                token_data = zoho_api.refresh_access_token(session['refresh_token'])
                if 'access_token' in token_data:
                    session['access_token'] = token_data['access_token']
                    session['expires_at'] = time.time() + token_data.get('expires_in', 3600)

        # 2. Fetch user info if missing
        if 'user_id' not in session or 'is_admin' not in session:
            try:
                user_info = zoho_api.fetch_user_info(session['access_token'])
                if 'users' in user_info and len(user_info['users']) > 0:
                    user = user_info['users'][0]
                    session['user_id'] = user['id']
                    session['user_name'] = user.get('full_name', user.get('last_name', 'Zoho User'))
                    profile = user.get('profile', {})
                    profile_name = profile.get('name', '')
                    session['is_admin'] = (profile_name.lower() in ['administrator', 'admin'])
                    log_debug(f"LOGIN INFO: Name={session['user_name']}, Profile={profile_name}, IsAdmin={session['is_admin']}, ID={session['user_id']}")
            except Exception as e:
                log_debug(f"DEBUG: Failed to fetch user info: {str(e)}")

        # 3. Detect org/domain — runs INDEPENDENTLY for every user when missing from session
        if 'org_id' not in session or 'domain_name' not in session:
            org_fetched = False
            try:
                org_info = zoho_api.fetch_org_metadata(session['access_token'])
                log_debug(f"DEBUG Org API raw response keys: {list(org_info.keys())} | code={org_info.get('code','?')}")
                if 'org' in org_info and len(org_info['org']) > 0:
                    org = org_info['org'][0]
                    log_debug(f"DEBUG: Full Org Data: {json.dumps(org)}")
                    session['org_id'] = org.get('zgid') or org.get('zoid') or org.get('id')
                    session['domain_name'] = org.get('domain_name', '')
                    org_fetched = True
                    log_debug(f"AUTO-DETECTED: OrgID={session['org_id']}, Domain={session['domain_name']}")
                    if session['org_id'] and not database.get_global_setting('crmplus_orgid', ''):
                        database.set_global_setting('crmplus_orgid', str(session['org_id']))
                        log_debug(f"Saved OrgID to global settings: {session['org_id']}")
                    if session['domain_name'] and not database.get_global_setting('crmplus_domain', ''):
                        database.set_global_setting('crmplus_domain', session['domain_name'])
                        log_debug(f"Saved Domain to global settings: {session['domain_name']}")
                else:
                    # v6 failed — try v3 as fallback
                    log_debug(f"Org v6 failed (code={org_info.get('code','?')}), trying v3...")
                    org_info_v3 = zoho_api.fetch_org_metadata_v3(session['access_token'])
                    log_debug(f"DEBUG Org v3 raw: {json.dumps(org_info_v3)[:300]}")
                    if 'org' in org_info_v3 and len(org_info_v3['org']) > 0:
                        org = org_info_v3['org'][0]
                        session['org_id'] = org.get('zgid') or org.get('zoid') or org.get('id')
                        session['domain_name'] = org.get('domain_name', '')
                        org_fetched = True
                        log_debug(f"AUTO-DETECTED (v3): OrgID={session['org_id']}, Domain={session['domain_name']}")
                        if session['org_id'] and not database.get_global_setting('crmplus_orgid', ''):
                            database.set_global_setting('crmplus_orgid', str(session['org_id']))
                        if session['domain_name'] and not database.get_global_setting('crmplus_domain', ''):
                            database.set_global_setting('crmplus_domain', session['domain_name'])
            except Exception as org_err:
                log_debug(f"DEBUG: Org API exception: {str(org_err)}")

            # Fallback: load from global DB (written by admin session)
            if not org_fetched:
                stored_org_id = database.get_global_setting('crmplus_orgid', '')
                stored_domain  = database.get_global_setting('crmplus_domain', '')
                if stored_org_id:
                    session['org_id'] = stored_org_id
                    log_debug(f"Loaded OrgID from global settings: {stored_org_id}")
                if stored_domain:
                    session['domain_name'] = stored_domain
                    log_debug(f"Loaded Domain from global settings: {stored_domain}")
                if not stored_org_id and not stored_domain:
                    log_debug("WARNING: org/domain not found via API or global settings. Admin must log in or set manually in Settings.")


@app.route('/')
def index():
    if 'access_token' not in session or not session.get('user_id'):
        return redirect(url_for('login'))
    
    # Priority: Manual Global Setting > Session Cache
    org_id = database.get_global_setting('crmplus_orgid', '') or session.get('org_id', 'Unknown')
    domain_name = database.get_global_setting('crmplus_domain', '') or session.get('domain_name', 'Unknown')
    is_manual = database.get_global_setting('crmplus_orgid', '') != '' or database.get_global_setting('crmplus_domain', '') != ''
    
    log_debug(f"--- MAP SESSION CONNECTED ---")
    log_debug(f"User: {session.get('user_name')} ({'Administrator' if session.get('is_admin') else 'Standard User'})")
    log_debug(f"CRM Plus Config: Domain={domain_name}, OrgID={org_id} ({'Manual Override' if is_manual else 'Auto-Detected'})")
    
    # show_console is a per-user session setting — admins can toggle it in Settings;
    # it is intentionally NOT a global setting so team users never see the console.
    show_console = session.get('show_console', False) and session.get('is_admin', False)
    effective_configs = database.get_effective_configs(session.get('user_id'))
    
    # Enrich configs with module_label (display name) from cached module list
    # so the data legend can match colors even when item.module shows display labels
    cached_modules_json = database.get_global_setting('cached_modules', '[]')
    try:
        module_labels = {m['api_name']: m.get('plural_label', m['api_name']) for m in json.loads(cached_modules_json) if 'api_name' in m}
        for c in effective_configs:
            c['module_label'] = module_labels.get(c['module_name'], c['module_name'])
    except Exception:
        pass
    
    is_admin = session.get('is_admin', False)
    return render_template('map.html',
        google_maps_api_key=GOOGLE_MAPS_API_KEY,
        configs=effective_configs,
        is_admin=is_admin
    )

@app.route('/login')
def login():
    # Dynamically select the redirect URI matching the current request host
    matched_uri = zoho_api.get_matching_redirect_uri(request.host_url)
    auth_url = zoho_api.get_authorization_url(redirect_uri=matched_uri)
    log_debug(f"Login initiated — using redirect_uri: {matched_uri}")
    return render_template('login.html', auth_url=auth_url)

@app.route('/callback')
def callback():
    code = request.args.get('code')
    if code:
        # Pick the redirect URI that matches the host the callback arrived on
        matched_uri = zoho_api.get_matching_redirect_uri(request.host_url)
        log_debug(f"OAuth callback received — using redirect_uri: {matched_uri}")
        token_data = zoho_api.exchange_code_for_token(code, redirect_uri=matched_uri)
        if 'access_token' in token_data:
            session['access_token'] = token_data['access_token']
            session['expires_at'] = time.time() + token_data.get('expires_in', 3600)
            if 'refresh_token' in token_data:
                session['refresh_token'] = token_data['refresh_token']
            
            # Fetch User Info to identify them uniquely
            user_info = zoho_api.fetch_user_info(session['access_token'])
            log_debug(f"DEBUG: Callback Raw user_info: {user_info}")
            if 'users' in user_info and len(user_info['users']) > 0:
                user = user_info['users'][0]
                session['user_id'] = user['id']
                session['user_name'] = user.get('full_name', user.get('last_name', 'Zoho User'))
                session['is_admin'] = user.get('profile', {}).get('name') == 'Administrator'
                log_debug(f"User logged in: {session['user_name']} ({session['user_id']}) - Admin: {session.get('is_admin')}")
                
                # Cache the admin's refresh_token globally so it can be used as a fallback
                # for team users who lack API scope (CRM profile API access disabled).
                # SECURITY: This token is ONLY used server-side, never exposed to the frontend.
                if session['is_admin'] and 'refresh_token' in token_data:
                    encrypted = encrypt_token(token_data['refresh_token'])
                    database.set_global_setting('admin_refresh_token', encrypted)
                    log_debug("Admin refresh token encrypted and cached for team user fallback sync.")
                
                # If user logged in via email fallback, try to resolve their real numeric CRM user ID
                # using the admin token. This is needed for the Owner.id filter in the fallback sync.
                if not session.get('is_admin') and '@' in str(session.get('user_id', '')):
                    try:
                        admin_token = _get_admin_access_token()
                        if admin_token:
                            user_email = session['user_id']
                            all_users = requests.get(
                                f"{zoho_api.ZOHO_API_URL}/crm/v3/users?type=AllUsers",
                                headers={'Authorization': f'Zoho-oauthtoken {admin_token}'},
                                timeout=8
                            ).json()
                            if 'users' in all_users:
                                for u in all_users['users']:
                                    if u.get('email', '').lower() == user_email.lower():
                                        session['user_id'] = u['id']
                                        session['user_email'] = user_email
                                        log_debug(f"Resolved team user email {user_email} -> CRM ID {u['id']}")
                                        break
                    except Exception as e:
                        log_debug(f"Could not resolve team user CRM ID: {e}")

                # Pre-cache franchise memberships for this user so the first sync is fast.
                # Run in background thread to avoid slowing down the login redirect.
                def _prefetch_franchises(uid):
                    try:
                        tok = _get_admin_access_token()
                        if tok:
                            result = _get_user_franchise_ids(uid, tok, force_refresh=True)
                            log_debug(f"[login] Franchise pre-cache for {uid}: {result.get('names', [])}")
                    except Exception as ex:
                        log_debug(f"[login] Franchise pre-cache failed: {ex}")

                import threading
                threading.Thread(target=_prefetch_franchises,
                                 args=(session['user_id'],), daemon=True).start()

            return redirect(url_for('index'))
    return "Error in Zoho Authentication", 400

@app.route('/logout')
def logout():
    # Revoke the token at Zoho's server BEFORE clearing the session.
    # This forces a fresh consent screen on next login so all current scopes are re-granted.
    # Without this, Zoho continues issuing tokens with OLD limited scopes even after re-login.
    refresh_token = session.get('refresh_token')
    if refresh_token:
        try:
            zoho_api.revoke_token(refresh_token)
            log_debug(f"OAuth token revoked for user: {session.get('user_name', 'unknown')}")
        except Exception as e:
            log_debug(f"Token revocation failed (non-fatal): {e}")
    session.clear()
    return redirect(url_for('login'))

@app.route('/settings')
def settings():
    if 'access_token' not in session:
        return redirect(url_for('login'))
    # Team users don't need settings — redirect them to the map
    if not session.get('is_admin', False):
        return redirect(url_for('index'))
    configs = database.get_all_module_configs(session.get('user_id'))
    shared_configs = database.get_shared_configs()
    show_console = database.get_global_setting('show_console', 'false') == 'true'
    crm_domain = database.get_global_setting('crmplus_domain', '')
    crm_org_id = database.get_global_setting('crmplus_orgid', '')
    is_admin = session.get('is_admin', False)
    return render_template('settings.html', 
                           configs=configs, 
                           shared_configs=shared_configs,
                           show_console=show_console,
                           crm_domain=crm_domain,
                           crm_org_id=crm_org_id,
                           is_admin=is_admin)

@app.route('/api/modules')
def get_modules():
    if 'access_token' not in session:
        return jsonify({'error': 'Unauthorized'}), 401
    
    metadata = zoho_api.fetch_module_metadata(session['access_token'])
    if 'modules' in metadata:
        modules = [{'api_name': m['api_name'], 'plural_label': m['plural_label']} for m in metadata['modules']]
        # Cache in DB so team users (who lack ZohoCRM.settings.all) can use it
        database.set_global_setting('cached_modules', json.dumps(modules))
        return jsonify(modules)
    
    # Fallback: serve cached module list written by an admin session
    cached = database.get_global_setting('cached_modules', '')
    if cached:
        log_debug("Serving cached module list for user without settings permission")
        return jsonify(json.loads(cached))
    
    log_debug(f"Module fetch failed: {metadata.get('code', '?')} - {metadata.get('message', '?')}")
    return jsonify({'error': 'Failed to fetch modules'}), 500

@app.route('/api/fields/<module_name>')
def get_fields(module_name):
    if 'access_token' not in session:
        return jsonify({'error': 'Unauthorized'}), 401
    
    metadata = zoho_api.fetch_module_fields(module_name, session['access_token'])
    if 'fields' in metadata:
        fields = [{'api_name': f['api_name'], 'display_label': f['display_label']} for f in metadata['fields']]
        # Cache per-module fields so team users can use them too
        database.set_global_setting(f'cached_fields_{module_name}', json.dumps(fields))
        return jsonify(fields)
    
    # Fallback: serve cached fields
    cached = database.get_global_setting(f'cached_fields_{module_name}', '')
    if cached:
        log_debug(f"Serving cached fields for {module_name} (no settings permission)")
        return jsonify(json.loads(cached))
    
    log_debug(f"Fields fetch failed for {module_name}: {metadata.get('code','?')}")
    return jsonify({'error': 'Failed to fetch fields'}), 500

@app.route('/api/settings/config', methods=['POST'])
def save_config():
    if 'access_token' not in session:
        return jsonify({'error': 'Unauthorized'}), 401
    
    data = request.json
    try:
        database.save_module_config(
            user_id=session.get('user_id'),
            module_name=data['module_name'],
            location_type='both',
            field_mappings=data['field_mappings'],
            marker_color=data['marker_color'],
            marker_icon=data.get('marker_icon', 'pin'),
            is_shared=data.get('is_shared', False)
        )
        return jsonify({'success': True})
    except Exception as e:
        log_debug(f"Error saving config: {str(e)}")
        return jsonify({'error': str(e)}), 500

@app.route('/api/settings/config/<module_name>', methods=['DELETE'])
def delete_config(module_name):
    if 'access_token' not in session:
        return jsonify({'error': 'Unauthorized'}), 401
    database.delete_module_config(session.get('user_id'), module_name)
    database.clear_module_records(session.get('user_id'), module_name)
    return jsonify({'success': True})

@app.route('/api/settings/global', methods=['POST'])
def save_global_setting():
    if 'access_token' not in session:
        return jsonify({'error': 'Unauthorized'}), 401
    if not session.get('is_admin', False):
        return jsonify({'error': 'Admin only'}), 403
    data = request.json
    key = data.get('key', '')
    value = data.get('value', '')

    # show_console is a per-user (session) setting, NOT a global DB setting.
    # Storing it globally would enable the console for ALL users, including
    # team users who should never see internal debug output.
    if key == 'show_console':
        session['show_console'] = (value == 'true')
        session.modified = True  # Force Flask to commit the session cookie
        return jsonify({'success': True})

    # All other keys (crmplus_domain, crmplus_orgid, etc.) are admin-only globals
    database.set_global_setting(key, value)
    return jsonify({'success': True})




@app.route('/api/preview-record/<module_name>')
def preview_record(module_name):
    if 'access_token' not in session:
        return jsonify({'error': 'Unauthorized'}), 401
    
    # Fetch 1 record to use for preview. We don't specify fields so we get all fields.
    data = zoho_api.fetch_module_records(module_name, session['access_token'], page=1)
    if 'data' not in data or len(data['data']) == 0:
        return jsonify({'error': 'No records found'}), 404
        
    return jsonify(data['data'][0])



def _get_admin_access_token():
    """Get a fresh admin access token using the best available refresh token.

    Priority order:
      1. ZOHO_REFRESH_TOKEN env var (set in systemd service — permanent, no browser login needed)
      2. DB-stored encrypted refresh token (set when an admin user logs in via OAuth)

    The access token is NEVER exposed to the frontend or sent to the client.
    """
    # ── Priority 1: env-var refresh token (server config, no human login needed) ──
    env_refresh = os.environ.get('ZOHO_REFRESH_TOKEN', '').strip()
    if env_refresh:
        try:
            token_data = zoho_api.refresh_access_token(env_refresh)
            if 'access_token' in token_data:
                return token_data['access_token']
            log_debug(f"[admin_token] ZOHO_REFRESH_TOKEN exchange failed: {token_data.get('error')} — "
                      "check the token is valid and has the correct scopes.")
        except Exception as e:
            log_debug(f"[admin_token] ZOHO_REFRESH_TOKEN exception: {e}")

    # ── Priority 2: DB-stored encrypted token (set when admin logs in via browser) ──
    encrypted = database.get_global_setting('admin_refresh_token', '')
    if not encrypted:
        return None
    refresh_token = decrypt_token(encrypted)
    if not refresh_token:
        log_debug("Admin token decryption failed — token may have been stored before encryption was enabled.")
        return None
    try:
        token_data = zoho_api.refresh_access_token(refresh_token)
        if 'access_token' in token_data:
            return token_data['access_token']
        log_debug(f"Admin token refresh failed: {token_data.get('error', 'unknown error')}")
    except Exception as e:
        log_debug(f"Admin token refresh exception: {e}")
    return None

def _require_admin_token(context='sync'):
    """Return admin access token for server-side API calls.
    All data syncs use the admin token so user profile API restrictions
    do not limit which modules/records can be fetched.
    Falls back to user session token if no admin token is stored yet."""
    token = _get_admin_access_token()
    if token:
        return token
    log_debug(f"[{context}] WARNING: No admin token — using user session token (degraded mode).")
    from flask import session as _s
    return _s.get('access_token')


def _get_user_franchise_ids(user_id, admin_token, force_refresh=False):
    """Return franchise memberships for a user via COQL (the only Zoho endpoint
    that returns multiuserlookup field values). Falls back to territory assignments.

    Returns a dict: {'ids': [...], 'names': [...], 'pirtek_ids': [...], 'debug': [...]}
    """
    import time
    cache_key = f'franchise_ids_{user_id}'
    _cached_raw = database.get_global_setting(cache_key, '')
    _cached_data = None
    if _cached_raw:
        try:
            _cached_data = json.loads(_cached_raw)
        except Exception:
            pass

    # Return fresh cache (< 4h) without hitting the API
    if not force_refresh and _cached_data:
        if time.time() - _cached_data.get('ts', 0) < 14400:
            return _cached_data

    if not admin_token:
        # Admin token unavailable — use stale cache rather than returning nothing
        if _cached_data:
            log_debug(f"[franchise_ids] Admin token unavailable — using stale cache for user {user_id}. "
                      "An admin user must log back in to refresh the token.")
            return _cached_data
        log_debug("[franchise_ids] Admin token unavailable AND no cache — franchise filter skipped. "
                  "An admin must log in to ZohoMap to store the admin refresh token.")
        return None

    debug_log = []
    found = {}

    # ── Strategy 1: COQL — only endpoint that returns multiuserlookup field values
    # Query franchises where this user is listed in Franchise_Standard_Users OR Franchise_Admin_User
    for coql in [
        f"SELECT id, Name, Pirtek_Franchise_ID FROM Franchises WHERE Franchise_Standard_Users = '{user_id}'",
        f"SELECT id, Name, Pirtek_Franchise_ID FROM Franchises WHERE Franchise_Admin_User = '{user_id}'"
    ]:
        try:
            result = zoho_api.coql_query(coql, admin_token)
            recs = result.get('data', [])
            debug_log.append(f'COQL "{coql[:60]}…": {len(recs)} hits')
            for rec in recs:
                fid = str(rec.get('id', ''))
                if fid and fid not in found:
                    found[fid] = {
                        'id': fid,
                        'name': rec.get('Name', ''),
                        'pirtek_id': rec.get('Pirtek_Franchise_ID', '') or ''
                    }
        except Exception as e:
            debug_log.append(f'COQL error: {e}')

    # ── Strategy 2: Territory-based fallback
    # If COQL finds nothing, derive franchise list from the user's territory assignments.
    # Territory names in this org match Franchise names (e.g. "Colorado Springs" → franchise "Colorado Springs").
    if not found:
        try:
            headers = {'Authorization': f'Zoho-oauthtoken {admin_token}'}
            resp = requests.get(
                f'{zoho_api.ZOHO_API_URL}/crm/v3/users/{user_id}',
                headers=headers, timeout=10
            )
            if resp.ok and resp.content:
                udata = resp.json()
                user_obj = udata.get('users', [{}])[0] if 'users' in udata else udata.get('user', {})
                territories = user_obj.get('territories', [])
                debug_log.append(f'Territory fallback: user has {len(territories)} territories: {[t.get("name") for t in territories]}')
                for t in territories:
                    tid = str(t.get('id', ''))
                    tname = t.get('name', '')
                    if tid and tname not in ('PIRTEK USA', 'Head Office'):
                        # Use territory ID as a proxy franchise identifier
                        found[f'territory_{tid}'] = {
                            'id': f'territory_{tid}',
                            'name': tname,
                            'pirtek_id': ''
                        }
        except Exception as e:
            debug_log.append(f'Territory fallback error: {e}')

    results = {
        'ids':       [v['id']        for v in found.values()],
        'names':     [v['name']      for v in found.values()],
        'pirtek_ids':[v['pirtek_id'] for v in found.values()],
        'debug':     debug_log,
        'ts':        time.time()
    }

    database.set_global_setting(cache_key, json.dumps(results))
    log_debug(f"[franchise_ids] user {user_id} → {len(results['ids'])} franchise(s): {results['names']}")

def do_sync_single_record(user_id, access_token, module_name, record_id, config):
    log_debug(f"Starting single sync for module: {module_name}, record: {record_id} for user {user_id}...")
    
    fields = config['field_mappings']
    fetch_fields = set()
    for k, v in fields.items():
        if k == 'additional_fields' and isinstance(v, list):
            fetch_fields.update([f for f in v if f])
        elif isinstance(v, str) and v:
            fetch_fields.add(v)
            
    title_field = fields.get('title_field')
    name_field = title_field if title_field else ('Account_Name' if module_name == 'Accounts' else ('Full_Name' if module_name in ['Leads', 'Contacts'] else 'Name'))
            
    fetch_fields.add(name_field)
    fetch_fields.add('id')
    fetch_fields_list = list(fetch_fields)
        
    field_metadata = zoho_api.fetch_module_fields(module_name, access_token)
    field_label_map = {}
    if 'fields' in field_metadata:
        for f in field_metadata['fields']:
            field_label_map[f['api_name']] = f['display_label']
    else:
        cached = database.get_global_setting(f'cached_fields_{module_name}', '')
        if cached:
            try:
                for f in json.loads(cached):
                    field_label_map[f['api_name']] = f['display_label']
            except: pass

    data = zoho_api.fetch_single_record(module_name, record_id, access_token, fetch_fields_list)
    
    if 'code' in data and data.get('status') == 'error':
        error_code = data.get('code')
        error_msg  = data.get('message', '')
        log_debug(f"Zoho API error for {module_name}/{record_id}: [{error_code}] {error_msg}")
        if error_code in ('NO_PERMISSION', 'EMPTY_RESPONSE', 'INVALID_JSON'):
            log_debug(f"Attempting admin token fallback for {record_id}...")
            admin_token = _get_admin_access_token()
            if admin_token and user_id:
                criteria = f"((Owner.id:equals:{user_id})and(id:equals:{record_id}))"
                owner_data = zoho_api.search_records(module_name, criteria, admin_token, fields=fetch_fields_list)
                if 'data' in owner_data and owner_data['data']:
                    data = owner_data
                else:
                    log_debug(f"Admin fallback returned 0 records for {module_name}/{record_id}.")
                    return False
            else:
                log_debug("No admin token available for fallback.")
                return False
        else:
            return False

    records_list = data.get('data', [])
    if not records_list:
        log_debug(f"Single sync failed: No records returned for {module_name} {record_id}. Raw response: {data}")
        return False
        
    record = records_list[0]
    
    lat, lng = None, None
    name_raw = record.get(name_field, record.get('Full_Name', record.get('Name', f"{module_name} {record.get('id')}")))
    name = str(extract_val(name_raw))
    
    lat_field = fields.get('latitude')
    lng_field = fields.get('longitude')
    if lat_field and lng_field and record.get(lat_field) and record.get(lng_field):
        try:
            lat = float(record[lat_field])
            lng = float(record[lng_field])
        except (ValueError, TypeError):
            pass
    
    if lat is None or lng is None:
        address_parts = []
        for k in ['address1', 'address2', 'city', 'state', 'zip', 'country']:
            val = extract_val(record.get(fields.get(k)))
            if val:
                address_parts.append(str(val))
        
        full_address = ", ".join(address_parts)
        if full_address:
            lat, lng = geocode_address(full_address)
    
    if lat is not None and lng is not None:
        record_data = {}
        lat_val = record.get(fields.get('latitude'))
        lng_val = record.get(fields.get('longitude'))
        if lat_val: record_data['Latitude'] = str(lat_val)
        if lng_val: record_data['Longitude'] = str(lng_val)

        addr1 = extract_val(record.get(fields.get('address1')))
        addr2 = extract_val(record.get(fields.get('address2')))
        full_addr = f"{addr1 or ''} {addr2 or ''}".strip()
        if full_addr: record_data['Address'] = full_addr
        
        for k, label in [('city', 'City'), ('state', 'State'), ('zip', 'Zip'), ('country', 'Country')]:
            val = extract_val(record.get(fields.get(k)))
            if val is not None and val != "": record_data[label] = str(val)

        for k in fetch_fields_list:
            if k in ['id', name_field] or k in fields.values():
                continue
            val = record.get(k)
            if val is not None and val != "":
                label = field_label_map.get(k, k.replace('_', ' '))
                record_data[label] = str(extract_val(val))
                
        # Store parent link ID for client-side deduplication (raw dict id, not display name)
        df = fields.get('duplicate_filter', {})
        if df.get('enabled') and df.get('parent_link_field'):
            raw_parent = record.get(df['parent_link_field'])
            if isinstance(raw_parent, dict) and 'id' in raw_parent:
                record_data['_dup_parent_id'] = raw_parent['id']
            elif raw_parent:
                record_data['_dup_parent_id'] = str(raw_parent)

        database.save_module_records_batch(user_id, [(
            record.get('id'),
            module_name,
            name,
            lat,
            lng,
            config['marker_color'],
            record_data
        )])
        
        log_debug(f"--- Raw Zoho API Data for {name} ({record_id}) ---")
        for k in fetch_fields_list:
            log_debug(f"RAW {k}: {record.get(k)}")

        log_debug(f"--- Extracted Record Data for {name} ({record_id}) ---")
        for k, v in record_data.items():
            log_debug(f"{k}: {v}")
        log_debug(f"--------------------------------------------------")
        
        log_debug(f"Successfully synced and saved single record: {name} ({record_id})")
        return True
    else:
        log_debug(f"Single sync failed: No valid location found for {name} ({record_id}). Record data: {record}")
        return False

@app.route('/api/sync-record/<module_name>/<record_id>', methods=['POST'])
def sync_single_record(module_name, record_id):
    if 'access_token' not in session:
        log_debug("Sync record failed: Unauthorized (no access_token in session)")
        return jsonify({'error': 'Unauthorized'}), 401
    
    configs = database.get_effective_configs(session.get('user_id'))
    config = next((c for c in configs if c['module_name'] == module_name), None)
    if not config:
        log_debug(f"Sync record failed: Module {module_name} not configured for user. Available: {[c['module_name'] for c in configs]}")
        return jsonify({'error': 'Module not configured'}), 404

    # Always use admin token so per-user API profile restrictions don't block the fetch
    sync_token = _require_admin_token(f'sync-record/{module_name}')
    if not sync_token:
        return jsonify({'error': 'Server not configured: no admin token available'}), 503

    try:
        success = do_sync_single_record(session.get('user_id'), sync_token, module_name, record_id, config)
        if success:
            log_debug(f"API /api/sync-record/{module_name}/{record_id} success.")
            return jsonify({'success': True})
        else:
            log_debug(f"API /api/sync-record/{module_name}/{record_id} failed.")
            return jsonify({'error': 'Failed to sync record (not found or no valid location)'}), 400
    except Exception as e:
        log_debug(f"Sync error: {str(e)}")
        import traceback
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500


def do_sync_module(user_id, access_token, module_name, config, is_admin=False):
    """Core logic to fetch, geocode, and save records for a single module.
    Non-admin users have records filtered to their assigned franchises."""
    log_debug(f"Starting sync for module: {module_name} for user {user_id} (admin={is_admin})...")
    database.clear_module_records(user_id, module_name)
    
    fields = config['field_mappings']
    
    fetch_fields = set()
    for k, v in fields.items():
        if k == 'additional_fields' and isinstance(v, list):
            fetch_fields.update([f for f in v if f])
        elif k == 'duplicate_filter':
            pass  # handled below
        elif isinstance(v, str) and v:
            fetch_fields.add(v)

    # Auto-include duplicate filter fields so they are stored in record_data
    df = fields.get('duplicate_filter', {})
    if df.get('enabled'):
        for key in ['parent_link_field', 'primary_code_field', 'override_checkbox_field']:
            v = df.get(key)
            if v:
                fetch_fields.add(v)
            
    title_field = fields.get('title_field')
    
    if title_field:
        name_field = title_field
    else:
        name_field = 'Name'
        if module_name == 'Accounts':
            name_field = 'Account_Name'
        elif module_name == 'Leads' or module_name == 'Contacts':
            name_field = 'Full_Name'
            
    fetch_fields.add(name_field)
    fetch_fields.add('id')
    
    fetch_fields_list = list(fetch_fields)

    # ── Franchise filter for non-admin users ──────────────────────────────────
    # Maps each module to its Franchise lookup field (confirmed from CRM Explorer)
    FRANCHISE_FIELD_MAP = {
        'Accounts':          'Franchise',
        'Leads':             'Select_Your_Franchise1',
        'Ship_To_Addresses': 'Franchise',
    }
    franchise_criteria = None
    if not is_admin:
        admin_token_for_lookup = _get_admin_access_token()
        # Guard: email user_id means admin token was expired at login (numeric ID not resolved)
        # Skip franchise filter — degrade to owner-based sync until admin re-logs in.
        if '@' in str(user_id):
            log_debug(f"[franchise filter] user_id is email ({user_id}) — admin token was expired "
                      "at login so numeric CRM ID was not resolved. Filter SKIPPED. "
                      "Admin must log back in to ZohoMap, then team user must re-login.")
            franchise_info = None  # skip to fallback path
            franchise_field = None
        else:
            franchise_info = _get_user_franchise_ids(user_id, admin_token_for_lookup)
            franchise_field = FRANCHISE_FIELD_MAP.get(module_name)

        if franchise_info is None:
            # Admin token unavailable, email-based ID, or no cache — degrade gracefully
            if '@' not in str(user_id):
                log_debug(f"[franchise filter] WARNING: Cannot determine franchises for {user_id}. "
                          "Admin token is invalid (Access Denied). "
                          "Log in as admin to ZohoMap to refresh it. Proceeding without franchise filter.")
        else:
            # Only use real Zoho record IDs (territory_ prefixed are fallback placeholders)
            franchise_ids = [fid for fid in franchise_info.get('ids', [])
                             if not str(fid).startswith('territory_')]
            if franchise_field and franchise_ids:
                ids_str = ','.join(franchise_ids)
                franchise_criteria = f"({franchise_field}.id:in:{ids_str})"
                log_debug(f"[franchise filter] {module_name}: "
                          f"{len(franchise_ids)} franchise(s): {franchise_info.get('names', [])}")
            elif franchise_field and not franchise_ids:
                # Check if territory fallback IDs exist (user has territories but no Franchise record link)
                territory_ids = [fid for fid in franchise_info.get('ids', [])
                                 if str(fid).startswith('territory_')]
                if territory_ids:
                    log_debug(f"[franchise filter] User has territory assignments but no Franchise record "
                              f"IDs — filter skipped, syncing all accessible records.")
                else:
                    log_debug(f"[franchise filter] User {user_id} has no franchise assignments. "
                              f"Returning empty sync for {module_name}.")
                    return 0
            else:
                log_debug(f"[franchise filter] No franchise field mapped for {module_name} — skipping filter")
    # ─────────────────────────────────────────────────────────────────────────

    field_metadata = zoho_api.fetch_module_fields(module_name, access_token)
    field_label_map = {}
    if 'fields' in field_metadata:
        for f in field_metadata['fields']:
            field_label_map[f['api_name']] = f['display_label']
        # Automatically cache fields for team user fallback
        try:
            fields_to_cache = [{'api_name': f['api_name'], 'display_label': f['display_label']} for f in field_metadata['fields']]
            database.set_global_setting(f'cached_fields_{module_name}', json.dumps(fields_to_cache))
        except Exception as e:
            log_debug(f"Failed to cache fields for {module_name}: {e}")
    else:
        # Team users lack permission to fetch fields, so fallback to the admin's globally cached fields
        cached = database.get_global_setting(f'cached_fields_{module_name}', '')
        if cached:
            try:
                cached_fields = json.loads(cached)
                for f in cached_fields:
                    field_label_map[f['api_name']] = f['display_label']
            except:
                pass
        
        log_debug(f"Warning: No 'fields' key in metadata for {module_name}. Response keys: {list(field_metadata.keys())}")
        if 'code' in field_metadata:
            log_debug(f"Metadata error: {field_metadata.get('code')} - {field_metadata.get('message')}")
    
    log_debug(f"Mapped {len(field_label_map)} labels for {module_name}. Samples: {list(field_label_map.keys())[:5]}")
        
    count = 0
    page = 1
    page_token = None
    more_records = True

    # Diagnostic — visible in debug.log and the in-app log console
    log_debug(f"[SYNC DIAG] module={module_name} user={user_id} is_admin={is_admin} "
              f"franchise_criteria={franchise_criteria!r}")

    while more_records:
        log_debug(f"Fetching page {page} for {module_name}...")

        # Use franchise criteria search for non-admins; full list for admins
        if franchise_criteria:
            data = zoho_api.search_records(module_name, franchise_criteria, access_token,
                                           fields=fetch_fields_list, page=page, page_token=page_token)
        else:
            data = zoho_api.fetch_module_records(module_name, access_token, fetch_fields_list,
                                                 page=page, page_token=page_token)

        log_debug(f"[SYNC DIAG] module={module_name} page={page} "
                  f"record_count={len(data.get('data', []))} "
                  f"error={data.get('code', 'none')} "
                  f"message={data.get('message', '')}")
        if 'code' in data and data.get('status') == 'error':
            error_code = data.get('code')
            log_debug(f"API Error fetching {module_name}: {error_code} - {data.get('message')}")
            
            # If NO_PERMISSION, try fetching with minimal fields to determine if it's FLS or Scope/Module Access
            if error_code == 'NO_PERMISSION':
                log_debug(f"Testing minimal fields (id, {name_field}) for {module_name} to check FLS...")
                minimal_data = zoho_api.fetch_module_records(module_name, access_token, ['id', name_field], page=page, page_token=page_token)
                if 'code' in minimal_data and minimal_data.get('status') == 'error':
                    log_debug(f"Minimal fields ALSO FAILED for {module_name}. CRM Profile has API Access disabled. Attempting admin-token fallback...")
                    
                    # ─────────────────────────────────────────────────────────────────────
                    # ADMIN TOKEN FALLBACK for Team Users with API Access disabled in CRM
                    #
                    # DATA PRIVACY RULES:
                    # 1. We ONLY fetch records where Owner.id == the team user's Zoho user ID.
                    #    The admin token gives broad access, but filtering by owner ensures
                    #    the team user ONLY sees their own assigned records.
                    # 2. Records are saved under the team user's user_id — never the admin's.
                    # 3. This fallback is ONLY triggered when the user's own token fails.
                    # ─────────────────────────────────────────────────────────────────────
                    admin_token = _get_admin_access_token()
                    if admin_token and user_id:
                        log_debug(f"Using admin token to fetch {module_name} records for {user_id} (franchise filter)")
                        # Use franchise criteria if available; otherwise fall back to owner filter
                        criteria = franchise_criteria or f"(Owner.id:equals:{user_id})"
                        owner_data = zoho_api.search_records(module_name, criteria, admin_token,
                                                             fields=fetch_fields_list, page=page, page_token=page_token)
                        if 'data' in owner_data and owner_data['data']:
                            data = owner_data
                            log_debug(f"Admin fallback returned {len(owner_data['data'])} records for {module_name} owned by {user_id}")
                        else:
                            log_debug(f"Admin fallback returned 0 records for {module_name} owned by {user_id}. Either no records assigned, or criteria filter failed.")
                            break
                    else:
                        log_debug(f"No admin token available for fallback. Admin must log in first.")
                        break
                else:
                    log_debug(f"Minimal fields SUCCEEDED for {module_name}! FLS issue — user cannot view one of: {fetch_fields_list}")
                    break
            else:
                break
            
        if 'data' not in data or not data['data']:
            break
            
        page_records = []
        for record in data['data']:
            lat, lng = None, None
            name_raw = record.get(name_field, record.get('Full_Name', record.get('Name', f"{module_name} {record.get('id')}")))
            name = str(extract_val(name_raw))
            
            # Prioritize Coordinates if available
            lat_field = fields.get('latitude')
            lng_field = fields.get('longitude')
            if lat_field and lng_field and record.get(lat_field) and record.get(lng_field):
                try:
                    lat = float(record[lat_field])
                    lng = float(record[lng_field])
                except (ValueError, TypeError):
                    pass
            
            # Fallback to Address if Coordinates failed or were missing
            if lat is None or lng is None:
                address_parts = []
                for k in ['address1', 'address2', 'city', 'state', 'zip', 'country']:
                    val = extract_val(record.get(fields.get(k)))
                    if val:
                        address_parts.append(str(val))
                
                full_address = ", ".join(address_parts)
                if full_address:
                    lat, lng = geocode_address(full_address)
            
            if lat is not None and lng is not None:
                record_data = {}
                
                # Add location info
                lat_val = record.get(fields.get('latitude'))
                lng_val = record.get(fields.get('longitude'))
                if lat_val: record_data['Latitude'] = str(lat_val)
                if lng_val: record_data['Longitude'] = str(lng_val)

                addr1 = extract_val(record.get(fields.get('address1')))
                addr2 = extract_val(record.get(fields.get('address2')))
                full_addr = f"{addr1 or ''} {addr2 or ''}".strip()
                if full_addr: record_data['Address'] = full_addr
                
                for k, label in [('city', 'City'), ('state', 'State'), ('zip', 'Zip'), ('country', 'Country')]:
                    val = extract_val(record.get(fields.get(k)))
                    if val is not None and val != "": record_data[label] = str(val)


                # 2. Add additional fields
                for k in fetch_fields_list:
                    # Skip fields we already handled or standard IDs
                    if k in ['id', name_field] or k in fields.values():
                        continue
                    
                    val = record.get(k)
                    if val is not None and val != "":
                        label = field_label_map.get(k, k.replace('_', ' '))
                        record_data[label] = str(extract_val(val))
                        
                page_records.append((
                    record.get('id'),
                    module_name,
                    name,
                    lat,
                    lng,
                    config['marker_color'],
                    record_data
                ))
                count += 1
            else:
                log_debug(f"Skipping record {record.get('id')} ({name}): No valid location found.")

        # Batch save the current page
        if page_records:
            database.save_module_records_batch(user_id, page_records)

        # Check for more records
        info = data.get('info', {})
        more_records = info.get('more_records', False)
        page_token = info.get('next_page_token')
        
        if more_records:
            page += 1
        
        # Extended safety break: 500 pages * 200 = 100,000 records max per module
        if page > 500:
            break

    log_debug(f"Sync complete! Saved {count} records for {module_name} (User: {user_id}).")
    return count

@app.route('/api/sync-module/<module_name>', methods=['POST'])
@limiter.limit("10 per minute")
def sync_module(module_name):
    if 'access_token' not in session:
        return jsonify({'error': 'Unauthorized'}), 401
    
    # Use effective configs so admins and team users can sync shared configs manually if needed
    configs = database.get_effective_configs(session.get('user_id'))
    config = next((c for c in configs if c['module_name'] == module_name), None)
    if not config:
        return jsonify({'error': 'Module not configured'}), 404

    # Always use admin token for module sync
    sync_token = _require_admin_token(f'sync-module/{module_name}')
    if not sync_token:
        return jsonify({'error': 'Server not configured: no admin token available'}), 503

    try:
        count = do_sync_module(session.get('user_id'), sync_token, module_name, config,
                               is_admin=session.get('is_admin', False))
        return jsonify({'success': True, 'synced': count})
    except Exception as e:
        log_debug(f"Sync error for {module_name}: {str(e)}")
        return jsonify({'error': str(e)}), 500

@app.route('/api/sync-all', methods=['POST'])
@limiter.limit("3 per minute")
def sync_all_modules():
    if 'access_token' not in session:
        return jsonify({'error': 'Unauthorized'}), 401
    
    # Use effective configs so team users can sync shared configs
    configs = database.get_effective_configs(session.get('user_id'))
    if not configs:
        return jsonify({'error': 'No modules configured to sync'}), 404

    # Always use admin token for all syncs
    sync_token = _require_admin_token('sync-all')
    if not sync_token:
        return jsonify({'error': 'Server not configured: no admin token available'}), 503

    results = {}
    total_synced = 0

    for config in configs:
        module_name = config['module_name']
        try:
            count = do_sync_module(session.get('user_id'), sync_token, module_name, config,
                                   is_admin=session.get('is_admin', False))
            results[module_name] = {'success': True, 'synced': count}
            total_synced += count
        except Exception as e:
            results[module_name] = {'error': str(e)}

    return jsonify({'success': True, 'total_synced': total_synced, 'details': results})



def sync_records_by_bounds(user_id, access_token, min_lat, max_lat, min_lng, max_lng):
    """
    Background sync for records in the current map viewport.

    DATA PRIVACY RULES — DO NOT CHANGE WITHOUT REVIEW:
    ────────────────────────────────────────────────────────────
    1. Records are fetched using the CALLER'S OWN access_token.
       Zoho enforces field-level and record-level CRM permissions on
       their side — the API will only return records the user can see.
    2. Records are ALWAYS saved under the caller's own user_id.
       Never save another user's records under a different user_id.
    3. get_effective_configs is used here ONLY to determine WHICH
       MODULES to sync (display configuration / field mappings).
       It does NOT grant access to another user's DATA.
    ────────────────────────────────────────────────────────────
    """
    # get_effective_configs returns the user's own configs merged with any
    # shared module configurations (field mappings, colors, etc.).
    # This tells us WHAT to sync — not WHOSE data to show.
    configs = database.get_effective_configs(user_id)
    total_new = 0
    
    for config in configs:
        module_name = config['module_name']
        fields = config['field_mappings']
        lat_field = fields.get('latitude')
        lng_field = fields.get('longitude')
        
        # Only modules with mapped lat/lng in Zoho can be searched by area
        if not lat_field or not lng_field:
            continue
            
        try:
            # Construct criteria: (Lat > min) AND (Lat < max) AND (Lng > min) AND (Lng < max)
            # Note: Criteria syntax might vary, using standard Zoho V3 pattern
            criteria = f"(({lat_field}:greater_than:{min_lat}) AND ({lat_field}:less_than:{max_lat}) AND ({lng_field}:greater_than:{min_lng}) AND ({lng_field}:less_than:{max_lng}))"
            
            # Fetch fields needed
            fetch_fields = set(['id', fields.get('title_field', 'Name')])
            for k, v in fields.items():
                if k == 'additional_fields' and isinstance(v, list):
                    fetch_fields.update([f for f in v if f])
                elif isinstance(v, str) and v:
                    fetch_fields.add(v)

            
            data = zoho_api.search_records(module_name, criteria, access_token, fields=list(fetch_fields))
            
            if 'data' not in data or not data['data']:
                continue
                
            new_records = []
            for record in data['data']:
                # Basic processing (similar to full sync but lighter)
                name_field = fields.get('title_field', 'Name')
                name = str(extract_val(record.get(name_field, '')))
                
                try:
                    lat = float(record[lat_field])
                    lng = float(record[lng_field])
                except:
                    continue # Skip if no valid coords returned
                
                # Build record_data for popup
                record_data = {}
                for k, v in record.items():
                    if k not in ['id', '$', 'Entity_Id']:
                        record_data[k] = str(extract_val(v))
                
                new_records.append((
                    record['id'],
                    module_name,
                    name,
                    lat,
                    lng,
                    config['marker_color'],
                    record_data
                ))
            
            if new_records:
                database.save_module_records_batch(user_id, new_records)
                total_new += len(new_records)
                
        except Exception as e:
            log_debug(f"Error in area-sync for {module_name}: {str(e)}")
            
    log_debug(f"Area sync finished. Added/Updated {total_new} records from Zoho.")
    return total_new

@app.route('/api/map-data')
@limiter.limit("120 per minute")
def get_map_data():
    if 'access_token' not in session:
        return jsonify({'error': 'Unauthorized'}), 401

    def _clamp(val, lo, hi):
        return max(lo, min(hi, val))

    try:
        min_lat = _clamp(float(request.args.get('min_lat', -90)), -90, 90)
        max_lat = _clamp(float(request.args.get('max_lat', 90)), -90, 90)
        min_lng = _clamp(float(request.args.get('min_lng', -180)), -180, 180)
        max_lng = _clamp(float(request.args.get('max_lng', 180)), -180, 180)
    except (ValueError, TypeError):
        return jsonify({'error': 'Invalid map bounds parameters'}), 400
    do_sync = request.args.get('sync', 'false').lower() == 'true'
    
    if do_sync:
        # Use sync-specific bounds if provided (capped at 200 miles by frontend)
        s_min_lat = float(request.args.get('sync_min_lat', min_lat))
        s_max_lat = float(request.args.get('sync_max_lat', max_lat))
        s_min_lng = float(request.args.get('sync_min_lng', min_lng))
        s_max_lng = float(request.args.get('sync_max_lng', max_lng))
        
        try:
            log_debug(f"Triggering background area-sync for user: {session.get('user_id')} (Capped Area: {s_min_lat} to {s_max_lat})")
            sync_records_by_bounds(session.get('user_id'), session['access_token'], s_min_lat, s_max_lat, s_min_lng, s_max_lng)
        except Exception as e:
            log_debug(f"WARNING: Area sync failed but continuing with local data: {str(e)}")
    
    log_debug(f"Querying local cache for area: Lat({min_lat} to {max_lat}), Lng({min_lng} to {max_lng}) (User: {session.get('user_id')})")
    
    # =========================================================================
    # DATA PRIVACY — CRITICAL: Records are ALWAYS scoped to the requesting
    # user's own user_id. We never mix records across users, regardless of
    # shared configurations or admin status. Shared configs define DISPLAY
    # settings only (which modules/fields to show, colors, icons). They do
    # NOT grant access to another user's synced record data.
    # If this line is changed to include other user_ids, it WILL expose
    # one user's CRM data to another user. Do not change without full review.
    # =========================================================================
    records = database.get_records_in_bounds(
        session.get('user_id'), min_lat, max_lat, min_lng, max_lng
    )
    

    log_debug(f"Found {len(records)} records in bounds.")
    
    # Get module labels and org info for display
    module_metadata = zoho_api.fetch_module_metadata(session['access_token'])
    # Priority: Manual Global Setting > Session Cache > Fresh API Fetch
    org_id = database.get_global_setting('crmplus_orgid', '') or session.get('org_id', '')
    domain_name = database.get_global_setting('crmplus_domain', '') or session.get('domain_name', '')
    
    # Only fetch from Zoho if still missing
    if not org_id or not domain_name:
        try:
            org_metadata = zoho_api.fetch_org_metadata(session['access_token'])
            if 'org' in org_metadata and len(org_metadata['org']) > 0:
                org = org_metadata['org'][0]
                if not org_id: org_id = org['zoid']
                if not domain_name: domain_name = org.get('domain_name', '')
        except:
            pass
            
    log_debug(f"DEBUG: Using OrgID={org_id}, Domain={domain_name}")

    module_label_map = {}
    module_url_map = {} # Map api_name to URL segment
    if 'modules' in module_metadata:
        for m in module_metadata['modules']:
            module_label_map[m['api_name']] = m['plural_label']
            # If it's a custom module, we might need a different identifier for the URL
            if m.get('generated_type') == 'custom':
                module_url_map[m['api_name']] = m['api_name'] # Default
                for key, value in m.items():
                    if isinstance(value, str) and 'CustomModule' in value:
                        module_url_map[m['api_name']] = value
                        break
            else:
                module_url_map[m['api_name']] = m['api_name']

    # Build a config lookup dict: for team users this includes shared configs automatically
    configs = {c['module_name']: c for c in database.get_effective_configs(session.get('user_id'))}
    

    map_points = []
    for r in records:
        cfg = configs.get(r['module_name'], {})
        
        # Build robust link for CRM or CRM Plus
        link_module = module_url_map.get(r['module_name'], r['module_name'])
        
        # If the Zoho API returned the OrgID as the domain name (which it does for standard CRM), ignore it.
        # We only want to use CRM Plus format if they actually have a custom domain name (like 'pirtekus').
        is_crm_plus = bool(domain_name and domain_name.lower() != 'unknown' and str(domain_name) != str(org_id) and str(domain_name) != f"org{org_id}")
        
        if org_id:
            # Prefix org_id with 'org' if it's purely numeric
            safe_org_id = f"org{org_id}" if str(org_id).isdigit() else org_id
            
            if is_crm_plus:
                # Modern CRM Plus / CX App format: /pirtekus/index.do/cxapp/crm/org897316137/tab/Leads/...
                zoho_link = f"https://crmplus.{ZOHO_TLD}/{domain_name}/index.do/cxapp/crm/{safe_org_id}/tab/{link_module}/{r['id']}"
            else:
                # Standard Zoho CRM format: /crm/org897316137/tab/Leads/...
                zoho_link = f"https://crm.{ZOHO_TLD}/crm/{safe_org_id}/tab/{link_module}/{r['id']}"
        else:
            zoho_link = f"https://crm.{ZOHO_TLD}/crm/tab/{link_module}/{r['id']}"

        map_points.append({
            'id': r['id'],
            'module': module_label_map.get(r['module_name'], r['module_name']),
            'api_module_name': r['module_name'],
            'zoho_link': zoho_link,
            'name': r['name'],
            'lat': r['lat'],
            'lng': r['lng'],
            'color': r['color'],
            'icon': cfg.get('marker_icon', 'pin'),
            'record_data': r['record_data'],
            'filter_config': cfg.get('field_mappings', {}).get('duplicate_filter')
        })

    return jsonify(map_points)

# ── CRM Explorer (admin diagnostic tool) ─────────────────────────────────────

@app.route('/admin/crm-explorer')
def crm_explorer_page():
    if not session.get('is_admin', False):
        return redirect('/')
    return render_template('crm_explorer.html',
                           user_name=session.get('user_name', ''),
                           is_admin=True)

def _admin_crm_get(path, params=None):
    """Make a GET request to Zoho CRM using the admin token."""
    token = _get_admin_access_token()
    if not token:
        return None, 'No admin token — an admin must log in first'
    headers = {'Authorization': f'Zoho-oauthtoken {token}'}
    url = f'{zoho_api.ZOHO_API_URL}{path}'
    try:
        resp = requests.get(url, headers=headers, params=params or {}, timeout=15)
        if not resp.content:
            return None, f'Empty response (HTTP {resp.status_code})'
        return resp.json(), None
    except Exception as e:
        return None, str(e)

@app.route('/api/admin/crm-modules')
def admin_crm_modules():
    if not session.get('is_admin', False):
        return jsonify({'error': 'Unauthorized'}), 403
    data, err = _admin_crm_get('/crm/v3/settings/modules')
    if err:
        return jsonify({'error': err}), 500
    modules = sorted([
        {'api_name': m['api_name'],
         'singular_label': m.get('singular_label', m['api_name']),
         'plural_label': m.get('plural_label', m['api_name'])}
        for m in data.get('modules', [])
    ], key=lambda x: x['plural_label'])
    return jsonify({'modules': modules})

@app.route('/api/admin/crm-fields/<module_name>')
def admin_crm_fields(module_name):
    if not session.get('is_admin', False):
        return jsonify({'error': 'Unauthorized'}), 403
    data, err = _admin_crm_get('/crm/v3/settings/fields', {'module': module_name})
    if err:
        return jsonify({'error': err}), 500
    fields = sorted([
        {'api_name': f['api_name'],
         'display_label': f.get('display_label', f['api_name']),
         'data_type': f.get('data_type', ''),
         'lookup': f.get('lookup', {}) or {},
         'formula': f.get('formula', {}) or {}}
        for f in data.get('fields', [])
    ], key=lambda x: x['display_label'])
    return jsonify({'module': module_name, 'fields': fields})

@app.route('/api/admin/crm-territories')
def admin_crm_territories():
    if not session.get('is_admin', False):
        return jsonify({'error': 'Unauthorized'}), 403
    token = _get_admin_access_token()
    if not token:
        return jsonify({'error': 'No admin token — an admin must log in first'}), 503
    headers = {'Authorization': f'Zoho-oauthtoken {token}'}
    base = zoho_api.ZOHO_API_URL

    results = {}
    # Try several endpoint variations used across Zoho CRM editions
    for path in ['/crm/v3/territories', '/crm/v2/territories',
                 '/crm/v3/settings/territories', '/crm/v2/settings/territories']:
        try:
            resp = requests.get(f'{base}{path}', headers=headers, timeout=10)
            raw = resp.text[:2000] if resp.text else '(empty)'
            results[path] = {'status': resp.status_code, 'raw': raw}
            if resp.ok and resp.content:
                try:
                    data = resp.json()
                    # Normalise: Zoho may use 'Territory' or 'territories' key
                    items = data.get('territories') or data.get('Territory') or data.get('data') or []
                    return jsonify({'territories': items, 'source_path': path, 'raw': data})
                except Exception:
                    pass
        except Exception as e:
            results[path] = {'status': 'exception', 'raw': str(e)}

    # All attempts failed — return the diagnostic info
    return jsonify({'territories': [], 'error': 'All territory endpoints failed', 'attempts': results})

@app.route('/api/admin/crm-users')
def admin_crm_users():
    if not session.get('is_admin', False):
        return jsonify({'error': 'Unauthorized'}), 403
    data, err = _admin_crm_get('/crm/v3/users', {'type': 'AllUsers'})
    if err:
        return jsonify({'error': err}), 500
    # Normalise: keep only what the explorer needs
    users = [
        {'id': u.get('id'),
         'name': u.get('full_name', u.get('name', '')),
         'email': u.get('email', ''),
         'role': u.get('role', {}).get('name', '') if isinstance(u.get('role'), dict) else '',
         'profile': u.get('profile', {}).get('name', '') if isinstance(u.get('profile'), dict) else '',
         'territories': u.get('territories', [])}
        for u in data.get('users', [])
    ]
    return jsonify({'users': users})

@app.route('/api/admin/test-franchise-lookup')
def admin_test_franchise_lookup():
    """Test franchise membership lookup for a user.
    Admins can look up any user_id via ?user_id=.
    Regular users can only look up their own ID."""
    if 'access_token' not in session:
        return jsonify({'error': 'Not logged in'}), 401
    is_admin = session.get('is_admin', False)
    requested_uid = request.args.get('user_id', session.get('user_id'))
    # Non-admins can only query themselves
    if not is_admin and requested_uid != session.get('user_id'):
        requested_uid = session.get('user_id')
    admin_token = _get_admin_access_token()
    if not admin_token:
        return jsonify({'error': 'No admin token available — an admin must log in first'}), 503

    # Run the normal lookup
    result = _get_user_franchise_ids(requested_uid, admin_token, force_refresh=True)

    # Also fetch first 3 raw records so we can inspect the field structure
    raw_sample = []
    try:
        headers = {'Authorization': f'Zoho-oauthtoken {admin_token}'}
        resp = requests.get(
            f'{zoho_api.ZOHO_API_URL}/crm/v3/Franchises',
            headers=headers,
            params={'fields': 'id,Name,Pirtek_Franchise_ID,Franchise_Admin_User,Franchise_Standard_Users',
                    'per_page': 3, 'page': 1},
            timeout=10
        )
        if resp.ok and resp.content:
            raw_sample = resp.json().get('data', [])
    except Exception as e:
        raw_sample = [{'error': str(e)}]

    return jsonify({'user_id': requested_uid, 'franchises': result, 'raw_sample': raw_sample})

if __name__ == '__main__':
    # NEVER run with debug=True in production — it exposes an interactive shell.
    is_debug = os.environ.get('FLASK_ENV', 'production') == 'development'
    app.run(host='0.0.0.0', port=5000, debug=is_debug)
