#!/bin/bash
# =============================================================================
# ZohoMap AWS Secrets Loader
# Pulls all application secrets from AWS Secrets Manager and writes them
# to /etc/zohomap/app.env so the zohomap.service can load them.
#
# Called automatically by zohomap-secrets.service at boot.
# Can also be run manually: sudo ./load_aws_secrets.sh
#
# Requirements:
#   - The EC2 instance must have an IAM role with secretsmanager:GetSecretValue
#   - awscli v2 must be installed (pre-installed on Amazon Linux / Ubuntu AMIs)
#   - The secret must be named: zohomap/production
# =============================================================================

set -e

SECRET_NAME="zohomap/production"
ENV_FILE="/etc/zohomap/app.env"
REGION="${AWS_DEFAULT_REGION:-$(curl -sf http://169.254.169.254/latest/meta-data/placement/region || echo 'us-east-1')}"

echo "[load_aws_secrets] Fetching secret '${SECRET_NAME}' from AWS Secrets Manager (region: ${REGION})..."

# Fetch the secret JSON from AWS
SECRET_JSON=$(aws secretsmanager get-secret-value \
    --secret-id "${SECRET_NAME}" \
    --region "${REGION}" \
    --query SecretString \
    --output text 2>&1)

if [ $? -ne 0 ]; then
    echo "[load_aws_secrets] ERROR: Failed to fetch secret from AWS Secrets Manager:"
    echo "$SECRET_JSON"
    exit 1
fi

# Validate it is valid JSON
echo "$SECRET_JSON" | python3 -m json.tool > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "[load_aws_secrets] ERROR: Secret value is not valid JSON. Check the format in AWS Secrets Manager."
    exit 1
fi

# Create the output directory
mkdir -p /etc/zohomap

# Parse JSON and write to env file using Python (available on all Ubuntu instances)
python3 - <<PYEOF
import json, sys

secret = json.loads('''${SECRET_JSON}''')

# Map of AWS secret keys -> env var names
# Add or rename keys here if your secret uses different names
KEY_MAP = {
    'APP_SECRET_KEY':       'APP_SECRET_KEY',
    'DATABASE_URI':         'DATABASE_URI',
    'ZOHO_CLIENT_ID':       'ZOHO_CLIENT_ID',
    'ZOHO_CLIENT_SECRET':   'ZOHO_CLIENT_SECRET',
    'ZOHO_REDIRECT_URI':    'ZOHO_REDIRECT_URI',
    'ZOHO_REFRESH_TOKEN':   'ZOHO_REFRESH_TOKEN',
    'GOOGLE_MAPS_API_KEY':  'GOOGLE_MAPS_API_KEY',
    'TOKEN_ENCRYPTION_KEY': 'TOKEN_ENCRYPTION_KEY',
}

lines = [
    '# Auto-generated by load_aws_secrets.sh — DO NOT EDIT MANUALLY',
    '# This file is overwritten at every service start from AWS Secrets Manager',
    '',
    'PATH=/var/www/zohomap/venv/bin',
    'FLASK_ENV=production',
]

missing = []
for aws_key, env_key in KEY_MAP.items():
    value = secret.get(aws_key, '').strip()
    if value:
        lines.append(f'{env_key}={value}')
    elif aws_key not in ('ZOHO_REFRESH_TOKEN',):  # Optional keys
        missing.append(aws_key)

if missing:
    print(f'[load_aws_secrets] WARNING: Missing keys in secret: {", ".join(missing)}', file=sys.stderr)

with open('${ENV_FILE}', 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f'[load_aws_secrets] Written {len(lines)} lines to ${ENV_FILE}')
PYEOF

# Lock down permissions — only root can read, www-data can read (for nightly sync)
chown root:www-data "${ENV_FILE}"
chmod 640 "${ENV_FILE}"

echo "[load_aws_secrets] Done! ${ENV_FILE} is ready."
